services:
  raccoon_sanctuary_db:
    image: mysql:8.0
    ports:
    - "4040:3306"
    environment:
      - MYSQL_DATABASE=raccoon_sanctuary
      - MYSQL_ROOT_PASSWORD=root
    volumes:
    - mysql_data:/var/lib/mysql
volumes:
  mysql_data: